Trivy scaner fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,13 +29,19 @@ jobs:
           fi
           echo "env.example OK"
           
-  skan_image:
+  scan_image:
     runs-on: ubuntu-latest
     needs: test
 
     steps:
+      - name: Code checkout                                         
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
+
+      - name: Build PHP image                                       
+        run: docker build -t clickykeys-php:latest ./php-fpm
+
       - name: Scan image with Trivy
-        uses: aquasecurity/trivy-action@master
+        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
         with:
           image-ref: 'clickykeys-php:latest'
           exit-code: '1'
@@ -44,7 +50,7 @@ jobs:
 
   deploy:
     runs-on: ubuntu-latest
-    needs: skan_image
+    needs: scan_image
 
     steps:
       - name: Deploy to Oracle VM
@@ -67,23 +73,17 @@ jobs:
 
             # Docker contener rebuild delay
             for i in $(seq 1 12); do
-              STATUS=$(curl -s -o /dev/null -w "%{http_code}" $DOMAIN)
-              [ "$STATUS" = "200" ] && { echo "OK"; break; }
-              [ $i -eq 12 ] && { echo "FAIL"; exit 1; }
+              STATUS=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.TEST_WEB_DOMAIN }})
+              if [ "$STATUS" = "200" ]; then
+                echo "Deploy OK — HTTP $STATUS"
+                exit 0
+              fi
               echo "Attempt $i — HTTP $STATUS, retry..."
               sleep 10
             done
 
-            # Web health check (HTTP 200)
-            HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.PROD_WEB_DOMAIN }})
-
-            if [ "$HTTP_STATUS" = "200" ]; then
-              echo "Deploy OK — HTTP $HTTP_STATUS"
-            else
-              echo "ERROR — HTTP $HTTP_STATUS, rollback..."
-              git reset --hard $PREVIOUS_COMMIT
-              docker compose up -d --build
-              echo "Rollback finished"
-              exit 1   # Return deploy fail
-            fi
-            
+            echo "ERROR — rollback to $PREVIOUS_COMMIT..."
+            git reset --hard $PREVIOUS_COMMIT
+            docker compose up -d --build
+            echo "Rollback finished"
+            exit 1           
